---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/keystone-services.html
- name: Add the Identity service > Create the service entity and API endpoint
  hosts: controller
  roles:
    - config
  sudo: True
  gather_facts: False
  # set the environment variables according to
  #  http://docs.ansible.com/ansible/playbooks_environment.html
  environment: "{{ config.environment.token }}"

  tasks:
  - name: "Create the service entity for the Identity service"
    shell: 'openstack service create --name keystone --description "OpenStack Identity" identity'

  - name: "Create the Identity service API endpoint"
    shell: "openstack endpoint create --publicurl {{ config.identity_public_url }} --internalurl {{ config.identity_internal_url }} --adminurl {{ config.identity_admin_url }} --region RegionOne identity"
