#!/bin/bash
#
# This script prints all variables defined by the installation_configuration.sh
# and all arguments.
# Example:
#     tools/config_variables a=1 b=2

environment_variables=`( set -o posix ; set ) | grep -o -e "^[^=']*"`" environment_variables"

source `dirname $0`/../config/installation_configuration.sh >> /dev/null

config_environment_variables=`( set -o posix ; set ) | grep -o -e "^[^=']*"`

for config_variable_name in $config_environment_variables
do
	found=false
	for variable_name in $environment_variables
	do
		if [ $config_variable_name == $variable_name ]
		then
			found=true
		fi
	done
	if [ $found == false ]
	then
		# this variable was added in config
		echo $config_variable_name=`eval echo \$\{${config_variable_name}\}`
	fi
done

for argument;
do
	echo $argument
done

