#!/bin/bash

# go to local directory so it is easier to target files
cd `dirname $0`

vm_name=$1
vm_folder=../config/vm/$vm_name

if ! ./vm_configuration_with_name_exists $vm_name $vm_folder
then
	exit 1
fi

source ../config/installation_configuration.sh

virsh destroy $vm_name > /dev/null
virsh undefine $vm_name > /dev/null

# copy the virtual machine image into the right folder
rm -f $vm_images_directory/${vm_name}.img
cp $vm_base_image_file $vm_images_directory/${vm_name}.img

# We create a new config file for every vm. 
# These are the files we use to store the vm config and images
user_data_vm_config_file=`dirname $user_data_cloud_config_file`/${vm_name}_`filename $user_data_cloud_config_file`
user_data_vm_config_image=`dirname $user_data_cloud_config_image`/${vm_name}_`filename $user_data_cloud_config_image`

# Create a user data file
if [ -f $user_data_vm_config_file ]
then
	rm -f $user_data_vm_config_file
fi

echo "#cloud-config
password: $authorized_password_for_access_to_the_vm
chpasswd: { expire: False }
hostname: $vm_name
manage_etc_hosts: true
ssh_pwauth: True
" > $user_data_vm_config_file

# In case we have a network configuration we copy it into the vm.
if [ -f $vm_folder/etc_network_interfaces ]
then
	# copy files: http://cloudinit.readthedocs.org/en/latest/topics/examples.html#writing-out-arbitrary-files
	# encode base64
	echo "write_files:
-   encoding: b64
    content: `cat $vm_folder/etc_network_interfaces | base64 -w0`
    owner: root:root
    path: /etc/network/interfaces
    permissions: '0644'" >> $user_data_vm_config_file
fi

echo "ssh_authorized_keys:
-   `cat $authorized_public_key_file_for_access_to_the_vm`" >> $user_data_vm_config_file

# Build the user-data image
# Now we convert the $user_data_cloud_config_file file to an ISO file.
rm -f $user_data_vm_config_image
~/cloud-utils/bin/cloud-localds $user_data_vm_config_image $user_data_vm_config_file

# from https://wiki.ubuntuusers.de/virsh
# create the virtual machine definition so it can be started
virsh define $vm_folder/creation.xml
