#!/bin/bash

vm_name=$1
vm_folder=$2

if [ $vm_name = '' ]
then
	>&2 echo expected name of virtual machine as first argument
	exit 1
fi

if [ ! -d $vm_folder ]
then
	>&2 echo did not find virtual machine configuration folder machine named $vm_name in $vm_folder
	exit 2
fi
