---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron-compute-node.html
- name:  "Add a networking component > Install and configure compute node > configure the Modular Layer 2 (ML2) plug-in"
  hosts: compute
  roles:
    - config
  sudo: True
  gather_facts: False
  tasks:

    # 1. Edit the /etc/neutron/plugins/ml2/ml2_conf.ini file

    - name: "1.a In the [ml2] section, enable the flat, VLAN, generic routing encapsulation (GRE), and virtual extensible LAN (VXLAN) network type drivers, GRE tenant networks, and the OVS mechanism driver"
      ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
                section=ml2
                option={{ item.option }}
                value={{ item.value }}
                backup=no
      with_items:
      - { option: 'type_drivers', value: 'flat,vlan,gre,vxlan' }
      - { option: 'tenant_network_types', value: 'gre' }
      - { option: 'mechanism_drivers', value: 'openvswitch' }

    - name: "1.b In the [ml2_type_gre] section, configure the tunnel identifier (id) range"
      ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
                section=ml2_type_gre
                option=tunnel_id_ranges
                value=1:1000
                backup=no

    - name: "1.c In the [securitygroup] section, enable security groups, enable ipset, and configure the OVS iptables firewall driver"
      ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
                section=securitygroup
                option={{ item.option }}
                value={{ item.value }}
                backup=no
      with_items:
      - { option: 'enable_security_group', value: 'True' }
      - { option: 'enable_ipset', value: 'True' }
      - { option: 'firewall_driver', value: 'neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver' }

    - name: 1.d.1 Get the host part of the IP 
      shell: echo {{ inventory_hostname }}
      register: host_ip

    - name: "1.d.2 In the [ovs] section, enable tunnels and configure the local tunnel endpoint:"
      ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
                section=ovs
                option={{ item.option }}
                value={{ item.value }}
                backup=no
      with_items:
      - { option: 'local_ip ', value: '{{ config.ip_tunnel_prefix }}.{{ host_ip.stdout.split(''.'')[3] }}' }

    - name: "1.e In the [agent] section, enable GRE tunnels"
      ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
                section=agent
                option=tunnel_types
                value=gre
                backup=no




