---
- include: playbooks/install_tools.yml
- include: playbooks/install_ansible.yml
- include: playbooks/libvirt.yml
- include: playbooks/copy_installation_script.yml
- include: playbooks/copy_experiment_scripts.yml
- include: playbooks/configure_iptables.yml
