Vagrant.configure("2") do |config|
  config.vm.define :datacenter do |datacenter|
    datacenter.vm.box = "sputnik13/trusty64"
    datacenter.vm.provider :libvirt do |domain|
      domain.memory = 6000
      domain.cpus = 2
      domain.nested = true
      domain.volume_cache = 'none'
    end
  end

	config.vm.provision :ansible do |ansible|
		ansible.playbook = "playbook.yml"
    # https://gist.github.com/phantomwhale/9657134
    ansible.raw_arguments = Shellwords.shellsplit(ENV['ANSIBLE_ARGS']) if ENV['ANSIBLE_ARGS']
	end
end
