#!/bin/bash

step_status=`cat step_status`

echo ---------------------------------------------------------
if [ "$step_status" = "0" ]
then
	echo running $@
	$@
	step_status=$?
	if [ $step_status != 0 ]
	then
		echo
		echo $@
		echo exit status $step_status
	fi
else
	echo skipping $@
fi

echo -n $step_status > step_status




