#!/bin/bash

vm_name=$1
vm_folder=$2

source `dirname $0`/../config/installation_configuration.sh

if [ $vm_name = '' ]
then
	>&2 echo expected name of virtual machine as first argument
	exit 1
fi

if [ ! -d $vm_folder ]
then
	>&2 echo did not find virtual machine configuration folder machine named $vm_name in $vm_folder
	exit 2
fi

if [ ! -f $vm_folder/creation.xml ]
then
	>&2 echo I need a $vm_folder/creation.xml file
	exit 3
fi

if [ ! -f $vm_folder/$user_data_cloud_config_file ]
then
	>&2 echo I need a $vm_folder/$user_data_cloud_config_file file
	exit 4
fi

if [ ! -f $vm_folder/etc_network_interfaces ]
then
	>&2 echo I need a $vm_folder/etc_network_interfaces file
	exit 4
fi

