---
- name:  "Add a networking component > Install and configure controller node > Verify operation"
  hosts: controller
  roles:
    - config
  sudo: True
  gather_facts: False
  tasks:

  # 1. Source the admin credentials to gain access to admin-only CLI commands

  - name: 2.1 Wait for neutron server to start
    # http://docs.ansible.com/ansible/wait_for_module.html
    wait_for: port=9696 connect_timeout=60
  
  - name: 2.1 List loaded extensions to verify successful launch of the neutron-server process
    shell: neutron ext-list
    environment: config.environment.admin
    register: neutron_ext_list

  - name: 2.1 Check that extensions are present
    assert:
      that: 
        - neutron_ext_list.stdout | search("\n\|\s*security-group")
        - neutron_ext_list.stdout | search("\n\|\s*l3_agent_scheduler")
        - neutron_ext_list.stdout | search("\n\|\s*net-mtu")
        - neutron_ext_list.stdout | search("\n\|\s*ext-gw-mode")
        - neutron_ext_list.stdout | search("\n\|\s*binding")
        - neutron_ext_list.stdout | search("\n\|\s*provider")
        - neutron_ext_list.stdout | search("\n\|\s*agent")
        - neutron_ext_list.stdout | search("\n\|\s*quotas")
        - neutron_ext_list.stdout | search("\n\|\s*subnet_allocation")
        - neutron_ext_list.stdout | search("\n\|\s*dhcp_agent_scheduler")
        - neutron_ext_list.stdout | search("\n\|\s*l3-ha")
        - neutron_ext_list.stdout | search("\n\|\s*multi-provider")
        - neutron_ext_list.stdout | search("\n\|\s*external-net")
        - neutron_ext_list.stdout | search("\n\|\s*router")
        - neutron_ext_list.stdout | search("\n\|\s*allowed-address-pairs")
        - neutron_ext_list.stdout | search("\n\|\s*extraroute")
        - neutron_ext_list.stdout | search("\n\|\s*extra_dhcp_opt")
        - neutron_ext_list.stdout | search("\n\|\s*dvr")

        # +-----------------------+-----------------------------------------------+
        # | alias                 | name                                          |
        # +-----------------------+-----------------------------------------------+
        # | security-group        | security-group                                |
        # | l3_agent_scheduler    | L3 Agent Scheduler                            |
        # | net-mtu               | Network MTU                                   |
        # | ext-gw-mode           | Neutron L3 Configurable external gateway mode |
        # | binding               | Port Binding                                  |
        # | provider              | Provider Network                              |
        # | agent                 | agent                                         |
        # | quotas                | Quota management support                      |
        # | subnet_allocation     | Subnet Allocation                             |
        # | dhcp_agent_scheduler  | DHCP Agent Scheduler                          |
        # | l3-ha                 | HA Router extension                           |
        # | multi-provider        | Multi Provider Network                        |
        # | external-net          | Neutron external network                      |
        # | router                | Neutron L3 Router                             |
        # | allowed-address-pairs | Allowed Address Pairs                         |
        # | extraroute            | Neutron Extra Route                           |
        # | extra_dhcp_opt        | Neutron Extra DHCP opts                       |
        # | dvr                   | Distributed Virtual Router                    |
        # +-----------------------+-----------------------------------------------+

 
